### PR TITLE
#133 Accumulator API integrated to all executors

### LINKED ISSUE #133: Accumulators: Integrate Accumulator API with all available executors
Currently the Accumulator API is fully supported only in `euphoria-flink` executor. If any accumulator is accessed on other executors an `IllegalStateException` is raised. See `cz.seznam.euphoria.core.client.io.Environment`.

Goal of this issue to add support to all available executors and then it should be possible to remove default implementation with `FIXME` from the `Environment` class.

### PR DESCRIPTION
**Pull request by vanekjar**
I removed the `FIXME` from the `Environment` class and implemented the accumulator support to all collectors in both remaining executors (Spark, in-mem).

closes #133

### CODE REVIEW

File: euphoria-spark/src/main/java/cz/seznam/euphoria/spark/UnaryFunctorWrapper.java [hunk 1]
```diff
@@ -26,31 +28,47 @@
 class UnaryFunctorWrapper<WID extends Window, IN, OUT>
         implements FlatMapFunction<SparkElement<WID, IN>, SparkElement<WID, OUT>> {
 
-  private final FunctionCollectorMem<OUT> context;
   private final UnaryFunctor<IN, OUT> functor;
+  private final AccumulatorProvider.Factory accumulatorFactory;
+  private final Settings settings;
 
-  public UnaryFunctorWrapper(UnaryFunctor<IN, OUT> functor) {
+  private FunctionCollectorMem<OUT> cachedCollector;
```
Comment (vanekjar) [inline euphoria-spark/src/main/java/cz/seznam/euphoria/spark/UnaryFunctorWrapper.java]: Yes, you're right. Theoretically this should be `transient`. It worked only because the collector is initially `null`. I'll fix it.
